import { Inter, Almarai } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const almarai = Almarai({ variable: "--font-sans-serif",subsets: ["arabic"],
  weight: [ "300", "400", "700", "800"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body className={`${inter.className} ${almarai.className} bg-body bg-cover bg-no-repeat`}>{children}</body>
    </html>
  );
}
